language: c
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      osx_image: xcode11
      compiler: clang
addons:
  apt:
    packages:
      - check
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - unzip
    update: true
  homebrew:
    packages:
      - check
      - meson
      - ninja
before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      python3 -m pip install --user meson;
      wget https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip;
      unzip ninja-linux.zip;
      sudo mv ninja /usr/local/bin/ninja;
    fi
script:
  - meson build
  - ninja -C build test
