language: c
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      compiler: clang
addons:
  apt:
    packages:
      - check
  homebrew:
    packages:
      - check
    update: true
script:
  - autoreconf -i
  - ./configure
  - make check
