language: c
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      compiler: clang
addons:
  apt:
    packages:
      - check
      - meson
      - ninja-build
  homebrew:
    packages:
      - check
      - meson
      - ninja
    update: true
script:
  - meson build
  - ninja -C build test
