language: c
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - os: osx
      compiler: clang
before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      sudo add-apt-repository -y ppa:deadsnakes/ppa;
      sudo apt-get update;
      sudo apt-get install ninja python3.6;
      curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6;
      pip3 install --user meson;
    fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew install ninja;
      brew upgrade python;
      pip3 install meson;
    fi
script:
  - meson build
  - ninja -C build test