language: c
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      osx_image: xcode11
      compiler: clang
    - os: osx
      osx_image: xcode11
      compiler: gcc-9
addons:
  apt:
    packages:
      - check
  homebrew:
    packages:
      - check
script:
  - ./autogen.sh
  - ./configure
  - make check
